# Generated by Django 4.1.2 on 2022-10-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="items.item",
            ),
            preserve_default=False,
        ),
    ]
